print("Which symbol would you like to use? :)")
l = input()
print("           ###########     ")
print("           #  ", l,l,"  #  ")
print("         < #    .    # >   ")
print("           # ------- #     ")
print("           ###########     ")
print("                ##         ")
print("       ################### ")
print("       #                 # ")
print(" *---- #    -       -    # ----* ")
print("       #                 # ")
print("       #                 # ")
print("       #                 # ")
print("       #                 # ")
print("       ################### ")
print("             |      |      ")
print("             |      |      ")
print("            _|_    _|_     ")