print("What is your name human?")
n = input()
print("How old are you?(in years)")
a = int(input())
print("How tall are you?(in metres)")
h = float (input())
print("How much do you weight?(in kg)")
w = float(input())
bmi = w/(h**2)
print(f"{n} you are {a} years old and your BMI is {bmi}")