print("Please enter number of lives.")
n = input ()
print("Please enter the energy level.")
n = input ()
print("Please enter the energy level.")
n = input ()
print("Please enter shield level.")
n = input ()
print("")
print("Health has been set.")
print("")
print("Lives: ♥♥♥")
print("Energy: ♦♦♦♦♦♦♦♦♦♦")
print("Shield: ♦♦♦♦♦♦♦")
#Added code to demonstrate the use of string operators.