print("Please enter number of lives.")
health = int(input())
print("Please enter the energy level.")
energy = int(input())
print("Please enter shield level.")
shield = int(input())
print("")
print("Health has been set.")
print("")
print("Lives:",  "\u2665"*health)
print("Energy:",   "\u2666"*energy)
print("Shield:",    "\u2666"*shield)
